# Generated by Django 4.2.27 on 2026-01-22 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0005_ensure_academy_currency'),
        ('students', '0003_parent_phone_numbers'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameModel(
                    old_name='Complaint',
                    new_name='Feedback',
                ),
                migrations.AlterModelOptions(
                    name='feedback',
                    options={
                        'db_table': 'tenant_complaints',
                        'ordering': ['-created_at'],
                        'verbose_name': 'Feedback',
                        'verbose_name_plural': 'Feedback',
                    },
                ),
                migrations.AlterField(
                    model_name='feedback',
                    name='academy',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback',
                        to='tenants.academy',
                    ),
                ),
                migrations.AlterField(
                    model_name='feedback',
                    name='assigned_to',
                    field=models.ForeignKey(
                        blank=True,
                        limit_choices_to={'role__in': ['ADMIN', 'OWNER']},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_feedback',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name='feedback',
                    name='parent',
                    field=models.ForeignKey(
                        limit_choices_to={'role': 'PARENT'},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='feedback',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AlterField(
                    model_name='feedback',
                    name='student',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='feedback',
                        to='students.student',
                    ),
                ),
            ],
        ),
    ]
