# Generated by Django 4.2.27 on 2026-01-19 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'db_table': 'tenant_terms',
                'indexes': [models.Index(fields=['academy', 'name'], name='tenant_term_academy_1d5990_idx'), models.Index(fields=['academy', 'start_date'], name='tenant_term_academy_ea8913_idx')],
                'unique_together': {('academy', 'name', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'db_table': 'tenant_sports',
                'indexes': [models.Index(fields=['academy', 'name'], name='tenant_spor_academy_48ccd4_idx')],
                'unique_together': {('academy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('SESSION', 'Session'), ('CUSTOM', 'Custom')], max_length=20)),
                ('duration_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_items', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Pricing Item',
                'verbose_name_plural': 'Pricing Items',
                'db_table': 'tenant_pricing_items',
                'indexes': [models.Index(fields=['academy', 'name'], name='tenant_pric_academy_2aae90_idx')],
                'unique_together': {('academy', 'name', 'duration_type')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'tenant_locations',
                'indexes': [models.Index(fields=['academy', 'name'], name='tenant_loca_academy_36120a_idx')],
                'unique_together': {('academy', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_categories', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Age Category',
                'verbose_name_plural': 'Age Categories',
                'db_table': 'tenant_age_categories',
                'indexes': [models.Index(fields=['academy', 'name'], name='tenant_age__academy_042899_idx')],
                'unique_together': {('academy', 'name')},
            },
        ),
    ]
