# Generated by Django 5.2.6 on 2026-03-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_checklist_item_timestamps'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='onboardingcheckliststate',
            new_name='tenant_onbo_academy_6728d1_idx',
            old_name='tenant_onbo_academy_8a4b4e_idx',
        ),
    ]
