# Generated by Django 5.2.6 on 2026-01-18 18:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('certifications', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='tenants.academy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
                'db_table': 'tenant_coaches',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['academy', 'email'], name='tenant_coac_academy_1fedf5_idx'), models.Index(fields=['academy', 'is_active'], name='tenant_coac_academy_b98a12_idx'), models.Index(fields=['user'], name='tenant_coac_user_id_e22d49_idx')],
                'constraints': [models.UniqueConstraint(fields=('academy', 'email'), name='unique_coach_email_per_academy'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',), name='unique_coach_user')],
            },
        ),
    ]
