# Generated by Django 5.2.6 on 2026-02-16 19:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('tenants', '0005_ensure_academy_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPayScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('SESSION', 'Per Session'), ('MONTH', 'Per Month'), ('WEEK', 'Per Week')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_pay_schemes', to='tenants.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_schemes', to='coaches.coach')),
            ],
            options={
                'verbose_name': 'Coach Pay Scheme',
                'verbose_name_plural': 'Coach Pay Schemes',
                'db_table': 'tenant_coach_pay_schemes',
                'ordering': ['coach', 'period_type'],
                'indexes': [models.Index(fields=['academy', 'coach'], name='tenant_coac_academy_fd54e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('coach', 'period_type'), name='unique_coach_pay_scheme_per_period')],
            },
        ),
    ]
