# Generated by Django 5.2.6 on 2026-02-16 20:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coach_pay_scheme'),
        ('tenants', '0005_ensure_academy_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('SESSION', 'Per Session'), ('MONTH', 'Per Month'), ('WEEK', 'Per Week')], db_index=True, max_length=20)),
                ('period_start', models.DateField(help_text='Week start, month start, or session date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_payments', to='tenants.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='coaches.coach')),
            ],
            options={
                'verbose_name': 'Coach Payment',
                'verbose_name_plural': 'Coach Payments',
                'db_table': 'tenant_coach_payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['academy', 'payment_date'], name='tenant_coac_academy_b50ff1_idx'), models.Index(fields=['coach', 'period_type', 'period_start'], name='tenant_coac_coach_i_ce210e_idx')],
            },
        ),
    ]
