# Generated by Django 5.2.6 on 2026-02-17 07:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coach_payment'),
        ('tenants', '0005_ensure_academy_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_description', models.CharField(max_length=255)),
                ('period_type', models.CharField(choices=[('SESSION', 'Per Session'), ('MONTH', 'Per Month'), ('WEEK', 'Per Week')], db_index=True, max_length=20)),
                ('period_start', models.DateField(help_text='Week start, month start, or session date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('issued_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invoices', to='tenants.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invoices', to='coaches.coach')),
            ],
            options={
                'db_table': 'tenant_staff_invoices',
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coachpayment',
            name='staff_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_payments', to='coaches.staffinvoice'),
        ),
        migrations.CreateModel(
            name='StaffReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_receipts', to='tenants.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_receipts', to='coaches.coach')),
                ('coach_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='coaches.coachpayment')),
                ('staff_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='coaches.staffinvoice')),
            ],
            options={
                'db_table': 'tenant_staff_receipts',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffinvoice',
            index=models.Index(fields=['academy', 'status'], name='tenant_staf_academy_e32642_idx'),
        ),
        migrations.AddIndex(
            model_name='staffinvoice',
            index=models.Index(fields=['academy', 'coach'], name='tenant_staf_academy_97fe08_idx'),
        ),
        migrations.AddIndex(
            model_name='staffinvoice',
            index=models.Index(fields=['academy', 'due_date'], name='tenant_staf_academy_892ab6_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffinvoice',
            constraint=models.UniqueConstraint(fields=('academy', 'invoice_number'), name='unique_staff_invoice_number_per_academy'),
        ),
        migrations.AddIndex(
            model_name='staffreceipt',
            index=models.Index(fields=['academy', 'receipt_number'], name='tenant_staf_academy_421c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='staffreceipt',
            index=models.Index(fields=['academy', 'coach'], name='tenant_staf_academy_03b21f_idx'),
        ),
        migrations.AddIndex(
            model_name='staffreceipt',
            index=models.Index(fields=['academy', 'payment_date'], name='tenant_staf_academy_d8692d_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffreceipt',
            constraint=models.UniqueConstraint(fields=('academy', 'receipt_number'), name='unique_staff_receipt_number_per_academy'),
        ),
    ]
