# Generated by Django 5.2.6 on 2026-03-23 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_staff_invoicing_and_receipts'),
        ('tenants', '0007_academy_global_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('SESSION', 'Session'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly')], db_index=True, max_length=20)),
                ('sessions_per_cycle', models.PositiveIntegerField(blank=True, help_text='Required for SESSION billing type.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('billing_day', models.PositiveIntegerField(blank=True, help_text='Required for MONTHLY billing type. Allowed range: 1-28.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('billing_day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Required for WEEKLY billing type. Monday=0, Sunday=6.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('cycle_start_date', models.DateField(help_text='Date when schedule cycle tracking starts.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_pay_schedules', to='tenants.academy')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_pay_schedules', to='coaches.coach')),
            ],
            options={
                'db_table': 'tenant_staff_pay_schedules',
                'ordering': ['coach', 'billing_type'],
            },
        ),
        migrations.CreateModel(
            name='CoachSessionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('sessions_counted', models.PositiveIntegerField(default=0)),
                ('last_counted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cycles', to='coaches.coach')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cycle', to='coaches.staffinvoice')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_cycles', to='coaches.staffpayschedule')),
            ],
            options={
                'db_table': 'tenant_coach_session_cycles',
            },
        ),
        migrations.AddField(
            model_name='staffinvoice',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Set if this invoice was auto-generated by a schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='coaches.staffpayschedule'),
        ),
        migrations.CreateModel(
            name='StaffPayScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('invoices_created', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('triggered_by', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual')], default='SCHEDULED', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='coaches.staffpayschedule')),
            ],
            options={
                'db_table': 'tenant_staff_pay_schedule_runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffpayschedule',
            index=models.Index(fields=['academy', 'is_active'], name='tenant_staf_academy_0b72a6_idx'),
        ),
        migrations.AddIndex(
            model_name='staffpayschedule',
            index=models.Index(fields=['academy', 'coach'], name='tenant_staf_academy_3268aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffpayschedule',
            constraint=models.UniqueConstraint(fields=('coach', 'billing_type'), name='unique_staff_pay_schedule_per_coach_billing_type'),
        ),
        migrations.AlterUniqueTogether(
            name='coachsessioncycle',
            unique_together={('schedule', 'coach', 'cycle_number')},
        ),
    ]
