# Generated by Django 5.2.6 on 2026-03-23 15:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_add_sport_location_to_class'),
        ('coaches', '0005_staffpayschedule_coachsessioncycle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffpayschedule',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='staffpayschedule',
            name='tenant_staf_academy_0b72a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='staffpayschedule',
            name='tenant_staf_academy_3268aa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='coachsessioncycle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffpayschedule',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-populated from CoachPayScheme; can be overridden here', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='staffpayschedule',
            name='class_scope',
            field=models.ForeignKey(blank=True, help_text='SESSION only - count sessions only for this class; null = all assigned classes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_pay_schedules', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='coachsessioncycle',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Null until this cycle fires; set on invoice generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_coach_cycle', to='coaches.staffinvoice'),
        ),
        migrations.AlterField(
            model_name='coachsessioncycle',
            name='last_counted_date',
            field=models.DateField(blank=True, help_text='Prevents double-counting on reruns', null=True),
        ),
        migrations.AlterField(
            model_name='coachsessioncycle',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cycles', to='coaches.staffpayschedule'),
        ),
        migrations.AlterField(
            model_name='staffpayschedule',
            name='billing_day',
            field=models.PositiveIntegerField(blank=True, help_text='MONTHLY only - day of month invoice fires', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AlterField(
            model_name='staffpayschedule',
            name='billing_day_of_week',
            field=models.PositiveIntegerField(blank=True, help_text='WEEKLY only - 0=Monday, 6=Sunday', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='staffpayschedule',
            name='billing_type',
            field=models.CharField(choices=[('SESSION', 'Per Session'), ('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffpayschedule',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_schedules', to='coaches.coach'),
        ),
        migrations.AlterField(
            model_name='staffpayschedule',
            name='cycle_start_date',
            field=models.DateField(help_text='Automation ignores attendance before this date'),
        ),
        migrations.AlterField(
            model_name='staffpayschedule',
            name='sessions_per_cycle',
            field=models.PositiveIntegerField(blank=True, help_text='SESSION only - how many sessions before invoice fires', null=True),
        ),
        migrations.AddConstraint(
            model_name='coachsessioncycle',
            constraint=models.UniqueConstraint(fields=('schedule', 'coach', 'cycle_number'), name='unique_coach_cycle_per_schedule'),
        ),
    ]
