# Generated by Django 5.2.6 on 2026-03-23 15:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_alter_staffpayschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffpayschedule',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Auto-populated from CoachPayScheme; can be overridden here', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
