# Generated by Django 5.2.6 on 2026-01-18 19:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.academy')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.parent')),
                ('parent_invoice', models.ForeignKey(blank=True, help_text='Link to parent invoice for visibility grouping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_invoices', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'tenant_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Billing Item',
                'verbose_name_plural': 'Billing Items',
                'db_table': 'tenant_billing_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='students.student')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='billing.item')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'tenant_invoice_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='tenants.academy')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'tenant_receipts',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['academy', 'status'], name='tenant_invo_academy_eea79e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['academy', 'parent'], name='tenant_invo_academy_0f356c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['academy', 'invoice_number'], name='tenant_invo_academy_b94166_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['academy', 'due_date'], name='tenant_invo_academy_b1ca4f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['parent', 'status'], name='tenant_invo_parent__7a9f65_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('academy', 'invoice_number'), name='unique_invoice_number_per_academy'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['academy', 'is_active'], name='tenant_bill_academy_c1b52d_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['academy', 'name'], name='tenant_bill_academy_300986_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice'], name='tenant_invo_invoice_b449a8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['item'], name='tenant_invo_item_id_25fb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['student'], name='tenant_invo_student_480f87_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['academy', 'receipt_number'], name='tenant_rece_academy_dca7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['academy', 'invoice'], name='tenant_rece_academy_edc5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['academy', 'payment_date'], name='tenant_rece_academy_e4c52e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['invoice', 'payment_date'], name='tenant_rece_invoice_3a6f11_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('academy', 'receipt_number'), name='unique_receipt_number_per_academy'),
        ),
    ]
