# Generated by Django 5.2.6 on 2026-01-21 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('onboarding', '0001_initial'),
        ('students', '0002_student_emirates_id'),
        ('tenants', '0002_onboardingstate_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='onboarding.location'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='onboarding.sport'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='onboarding.location'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='onboarding.sport'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['academy', 'sport'], name='tenant_invo_academy_8f6209_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['academy', 'location'], name='tenant_invo_academy_49115f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['academy', 'sport'], name='tenant_rece_academy_53fd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['academy', 'location'], name='tenant_rece_academy_f1ff10_idx'),
        ),
    ]
