# Generated by Django 5.2.6 on 2026-03-23 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_location_invoice_sport_receipt_location_and_more'),
        ('classes', '0004_add_sport_location_to_class'),
        ('students', '0003_parent_phone_numbers'),
        ('tenants', '0007_academy_global_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('SESSION_BASED', 'Session Based')], max_length=20)),
                ('sessions_per_cycle', models.PositiveIntegerField(blank=True, null=True)),
                ('bill_absent_sessions', models.BooleanField(default=False)),
                ('billing_day', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('cycle_start_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_schedules', to='tenants.academy')),
                ('billing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_schedules', to='billing.item')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_schedules', to='classes.class')),
            ],
            options={
                'db_table': 'tenant_invoice_schedules',
                'unique_together': {('academy', 'class_obj')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Set if this invoice was auto-generated by a schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='billing.invoiceschedule'),
        ),
        migrations.CreateModel(
            name='InvoiceScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('invoices_created', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('triggered_by', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual')], default='SCHEDULED', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='billing.invoiceschedule')),
            ],
            options={
                'db_table': 'tenant_invoice_schedule_runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoiceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('sessions_counted', models.PositiveIntegerField(default=0)),
                ('last_counted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cycle', to='billing.invoice')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_cycles', to='billing.invoiceschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_cycles', to='students.student')),
            ],
            options={
                'db_table': 'tenant_student_invoice_cycles',
                'unique_together': {('schedule', 'student', 'cycle_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_overrides', to='billing.invoiceschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='students.student')),
            ],
            options={
                'db_table': 'tenant_student_schedule_overrides',
                'unique_together': {('schedule', 'student')},
            },
        ),
    ]
