# Generated by Django 4.2.29 on 2026-03-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoiceschedule_invoice_schedule_invoiceschedulerun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceschedule',
            name='invoice_creation_timing',
            field=models.CharField(choices=[('AUTO', 'Auto (backwards compatible)'), ('START_OF_PERIOD', 'Start of month/session'), ('ON_COMPLETION', 'When month/session is completed')], db_index=True, default='AUTO', help_text='When draft invoices should be generated for this schedule.', max_length=30),
        ),
    ]
