# Generated by Django 4.2.29 on 2026-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoiceschedule_invoice_creation_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_link',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_s3_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf_s3_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
