# Generated by Django 4.2.29 on 2026-03-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_academywhatsappconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], db_index=True, max_length=16)),
                ('doc_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt')], db_index=True, max_length=16)),
                ('object_id', models.PositiveIntegerField()),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, max_length=16)),
                ('wa_message_id', models.CharField(blank=True, max_length=128)),
                ('error_detail', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tenants.academy')),
            ],
            options={
                'db_table': 'tenant_notification_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['academy', 'channel', 'status'], name='tenant_noti_academy_81ed21_idx'), models.Index(fields=['doc_type', 'object_id'], name='tenant_noti_doc_typ_fe0b3c_idx')],
            },
        ),
    ]
