# Generated by Django 5.2.6 on 2026-02-10 16:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onboarding', '0001_initial'),
        ('tenants', '0005_ensure_academy_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('bill_number', models.CharField(blank=True, default='', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='tenants.academy')),
            ],
            options={
                'db_table': 'tenant_bills',
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_type', models.CharField(choices=[('DAY', 'Per Day'), ('MONTH', 'Per Month'), ('SESSION', 'Per Session')], db_index=True, default='MONTH', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_rent_configs', to='tenants.academy')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_rent_configs', to='onboarding.location')),
            ],
            options={
                'db_table': 'tenant_facility_rent_configs',
                'ordering': ['location__name', 'period_type'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reorder_level', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='tenants.academy')),
            ],
            options={
                'db_table': 'tenant_inventory_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='facilities.bill')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_line_items', to='facilities.inventoryitem')),
            ],
            options={
                'db_table': 'tenant_bill_line_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('period_description', models.CharField(max_length=255)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_invoices', to='tenants.academy')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_invoices', to='onboarding.location')),
            ],
            options={
                'db_table': 'tenant_rent_invoices',
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='facilities.rentinvoice')),
            ],
            options={
                'db_table': 'tenant_rent_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['academy', 'status'], name='tenant_bill_academy_425992_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['academy', 'bill_date'], name='tenant_bill_academy_38625e_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['academy', 'due_date'], name='tenant_bill_academy_acaf83_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('bill_number__isnull', False), models.Q(('bill_number', ''), _negated=True)), fields=('academy', 'bill_number'), name='unique_bill_number_per_academy_when_set'),
        ),
        migrations.AddIndex(
            model_name='facilityrentconfig',
            index=models.Index(fields=['academy', 'location'], name='tenant_faci_academy_015cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityrentconfig',
            index=models.Index(fields=['academy', 'is_active'], name='tenant_faci_academy_1470a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilityrentconfig',
            constraint=models.UniqueConstraint(fields=('academy', 'location', 'period_type'), name='unique_facility_rent_config_per_period'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['academy', 'name'], name='tenant_inve_academy_1b9856_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['academy', 'quantity'], name='tenant_inve_academy_4e1f85_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('academy', 'name'), name='unique_inventory_item_name_per_academy'),
        ),
        migrations.AddIndex(
            model_name='billlineitem',
            index=models.Index(fields=['bill'], name='tenant_bill_bill_id_7121c4_idx'),
        ),
        migrations.AddIndex(
            model_name='billlineitem',
            index=models.Index(fields=['inventory_item'], name='tenant_bill_invento_ba2193_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['academy', 'status'], name='tenant_rent_academy_674ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['academy', 'location'], name='tenant_rent_academy_ac85b5_idx'),
        ),
        migrations.AddIndex(
            model_name='rentinvoice',
            index=models.Index(fields=['academy', 'due_date'], name='tenant_rent_academy_730846_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentinvoice',
            constraint=models.UniqueConstraint(fields=('academy', 'invoice_number'), name='unique_rent_invoice_number_per_academy'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['rent_invoice', 'payment_date'], name='tenant_rent_rent_in_433992_idx'),
        ),
    ]
