# Generated by Django 5.2.6 on 2026-02-17 07:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_bill_bill_date_alter_rentinvoice_issued_date_and_more'),
        ('tenants', '0005_ensure_academy_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHECK', 'Check'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_receipts', to='tenants.academy')),
                ('rent_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='facilities.rentinvoice')),
                ('rent_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='facilities.rentpayment')),
            ],
            options={
                'db_table': 'tenant_rent_receipts',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['academy', 'receipt_number'], name='tenant_rent_academy_543016_idx'), models.Index(fields=['academy', 'rent_invoice'], name='tenant_rent_academy_da90a3_idx'), models.Index(fields=['academy', 'payment_date'], name='tenant_rent_academy_7bf588_idx')],
                'constraints': [models.UniqueConstraint(fields=('academy', 'receipt_number'), name='unique_rent_receipt_number_per_academy')],
            },
        ),
    ]
