# Generated by Django 5.2.6 on 2026-03-23 21:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_add_rent_receipt'),
        ('onboarding', '0004_rent_pay_schedule_core'),
        ('tenants', '0007_academy_global_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAILY', 'Daily'), ('SESSION', 'Per Session')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Auto-populated from FacilityRentConfig; override here if needed', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('sessions_per_invoice', models.PositiveIntegerField(blank=True, help_text='SESSION only — how many sessions before invoice fires', null=True)),
                ('billing_day', models.PositiveIntegerField(blank=True, help_text='MONTHLY only — day of month invoice fires', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('due_date_offset_days', models.PositiveIntegerField(default=30, help_text='Days after issued_date to set as due_date (e.g. 30 = NET 30)')),
                ('cycle_start_date', models.DateField(help_text='Automation ignores classes/dates before this date')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_pay_schedules', to='tenants.academy')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_pay_schedules', to='onboarding.location')),
            ],
            options={
                'db_table': 'tenant_rent_pay_schedules',
            },
        ),
        migrations.CreateModel(
            name='FacilitySessionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(default=1)),
                ('sessions_counted', models.PositiveIntegerField(default=0)),
                ('last_counted_date', models.DateField(blank=True, help_text='Prevents double-counting on reruns', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, help_text='Null until cycle fires; set on invoice generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_facility_cycle', to='facilities.rentinvoice')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cycles', to='facilities.rentpayschedule')),
            ],
            options={
                'db_table': 'tenant_facility_session_cycles',
            },
        ),
        migrations.AddField(
            model_name='rentinvoice',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Set if this invoice was auto-generated by a rent pay schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='facilities.rentpayschedule'),
        ),
        migrations.CreateModel(
            name='RentPayScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('invoices_created', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=20)),
                ('triggered_by', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual')], default='SCHEDULED', max_length=20)),
                ('error_detail', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='facilities.rentpayschedule')),
            ],
            options={
                'db_table': 'tenant_rent_pay_schedule_runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rentpayschedule',
            constraint=models.UniqueConstraint(fields=('academy', 'location', 'billing_type'), name='unique_rent_pay_schedule_per_location_billing_type'),
        ),
        migrations.AddConstraint(
            model_name='facilitysessioncycle',
            constraint=models.UniqueConstraint(fields=('schedule', 'cycle_number'), name='unique_facility_cycle_per_schedule'),
        ),
    ]
