# Generated by Django 4.2.27 on 2026-01-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mediafile',
            new_name='tenant_medi_academy_3d4557_idx',
            old_name='tenant_medi_academy_idx',
        ),
        migrations.RenameIndex(
            model_name='mediafile',
            new_name='tenant_medi_academy_55cbc8_idx',
            old_name='tenant_medi_academy_created_idx',
        ),
        migrations.RenameIndex(
            model_name='mediafile',
            new_name='tenant_medi_file_na_8b72ef_idx',
            old_name='tenant_medi_file_nam_idx',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='class_obj',
            field=models.ForeignKey(blank=True, help_text='Class this media file is associated with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='classes.class'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['academy', 'class_obj'], name='tenant_medi_academy_8b0a09_idx'),
        ),
    ]
