# Generated by Django 4.2.29 on 2026-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_tenant_medi_academy_idx_tenant_medi_academy_3d4557_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='capture_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date when this media was captured', null=True),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['academy', 'capture_date'], name='tenant_medi_academy_ca717a_idx'),
        ),
    ]
