"""Facilities and academy running cost models."""
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import Q, Sum
from django.utils import timezone

from saas_platform.tenants.models import Academy
from tenant.billing.models import Receipt
from tenant.onboarding.models import Location


class FacilityRentConfig(models.Model):
    """Default rent setup per location."""

    class PeriodType(models.TextChoices):
        DAY = 'DAY', 'Per Day'
        MONTH = 'MONTH', 'Per Month'
        SESSION = 'SESSION', 'Per Session'

    academy = models.ForeignKey(
        Academy,
        on_delete=models.CASCADE,
        related_name='facility_rent_configs',
        db_index=True,
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        related_name='facility_rent_configs',
        db_index=True,
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
    )
    currency = models.CharField(max_length=3, default='USD')
    period_type = models.CharField(
        max_length=20,
        choices=PeriodType.choices,
        default=PeriodType.MONTH,
        db_index=True,
    )
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_facility_rent_configs'
        ordering = ['location__name', 'period_type']
        indexes = [
            models.Index(fields=['academy', 'location']),
            models.Index(fields=['academy', 'is_active']),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['academy', 'location', 'period_type'],
                name='unique_facility_rent_config_per_period',
            )
        ]

    def __str__(self):
        return f"{self.location.name} - {self.period_type}"

    def clean(self):
        if self.location_id and self.academy_id and self.location.academy_id != self.academy_id:
            raise ValidationError({'location': 'Location must belong to the same academy.'})


class RentInvoice(models.Model):
    """Rent invoice for a facility/location."""

    class Status(models.TextChoices):
        DRAFT = 'DRAFT', 'Draft'
        PENDING = 'PENDING', 'Pending'
        PAID = 'PAID', 'Paid'
        OVERDUE = 'OVERDUE', 'Overdue'
        CANCELLED = 'CANCELLED', 'Cancelled'

    academy = models.ForeignKey(
        Academy,
        on_delete=models.CASCADE,
        related_name='rent_invoices',
        db_index=True,
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.PROTECT,
        related_name='rent_invoices',
        db_index=True,
    )
    invoice_number = models.CharField(max_length=100, db_index=True)
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
    )
    currency = models.CharField(max_length=3, default='USD')
    period_description = models.CharField(max_length=255)
    issued_date = models.DateField(default=timezone.localdate)
    due_date = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.DRAFT,
        db_index=True,
    )
    notes = models.TextField(blank=True)
    schedule = models.ForeignKey(
        'RentPaySchedule',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='generated_invoices',
        help_text='Set if this invoice was auto-generated by a rent pay schedule',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_rent_invoices'
        ordering = ['-issued_date', '-created_at']
        indexes = [
            models.Index(fields=['academy', 'status']),
            models.Index(fields=['academy', 'location']),
            models.Index(fields=['academy', 'due_date']),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['academy', 'invoice_number'],
                name='unique_rent_invoice_number_per_academy',
            )
        ]

    def __str__(self):
        return f"{self.invoice_number} - {self.location.name}"

    def clean(self):
        if self.location_id and self.academy_id and self.location.academy_id != self.academy_id:
            raise ValidationError({'location': 'Location must belong to the same academy.'})

    def get_paid_amount(self):
        paid = self.payments.aggregate(total=Sum('amount')).get('total')
        return paid or Decimal('0.00')

    def get_remaining_amount(self):
        remaining = self.amount - self.get_paid_amount()
        return remaining if remaining > Decimal('0.00') else Decimal('0.00')

    def update_status(self):
        if self.status == self.Status.CANCELLED:
            return

        paid_amount = self.get_paid_amount()
        today = timezone.now().date()

        if paid_amount >= self.amount:
            self.status = self.Status.PAID
            return

        if self.due_date and self.due_date < today:
            self.status = self.Status.OVERDUE
            return

        if self.status == self.Status.DRAFT and paid_amount == Decimal('0.00'):
            return

        self.status = self.Status.PENDING


class RentPayment(models.Model):
    """Payment against a rent invoice."""

    rent_invoice = models.ForeignKey(
        RentInvoice,
        on_delete=models.CASCADE,
        related_name='payments',
        db_index=True,
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))],
    )
    payment_date = models.DateField(default=timezone.localdate)
    payment_method = models.CharField(
        max_length=20,
        choices=Receipt.PaymentMethod.choices,
    )
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_rent_payments'
        ordering = ['-payment_date', '-created_at']
        indexes = [
            models.Index(fields=['rent_invoice', 'payment_date']),
        ]

    def __str__(self):
        return f"{self.rent_invoice.invoice_number} - {self.amount}"

    def clean(self):
        if self.rent_invoice.status == RentInvoice.Status.CANCELLED:
            raise ValidationError({'rent_invoice': 'Cannot add payment to a cancelled rent invoice.'})

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
        invoice = self.rent_invoice
        invoice.update_status()
        invoice.save(update_fields=['status', 'updated_at'])

    def delete(self, *args, **kwargs):
        invoice = self.rent_invoice
        super().delete(*args, **kwargs)
        invoice.update_status()
        invoice.save(update_fields=['status', 'updated_at'])


class RentReceipt(models.Model):
    """Receipt for a rent payment; one-to-one with RentPayment."""

    academy = models.ForeignKey(
        Academy,
        on_delete=models.CASCADE,
        related_name='rent_receipts',
        db_index=True,
    )
    rent_invoice = models.ForeignKey(
        RentInvoice,
        on_delete=models.CASCADE,
        related_name='receipts',
        db_index=True,
    )
    rent_payment = models.OneToOneField(
        RentPayment,
        on_delete=models.CASCADE,
        related_name='receipt',
        db_index=True,
    )
    receipt_number = models.CharField(max_length=100, db_index=True)
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))],
    )
    payment_method = models.CharField(
        max_length=20,
        choices=Receipt.PaymentMethod.choices,
    )
    payment_date = models.DateField(default=timezone.localdate)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_rent_receipts'
        ordering = ['-payment_date', '-created_at']
        indexes = [
            models.Index(fields=['academy', 'receipt_number']),
            models.Index(fields=['academy', 'rent_invoice']),
            models.Index(fields=['academy', 'payment_date']),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['academy', 'receipt_number'],
                name='unique_rent_receipt_number_per_academy',
            )
        ]

    def __str__(self):
        return f"{self.receipt_number} - {self.amount}"

    def clean(self):
        if self.rent_invoice_id and self.academy_id and self.rent_invoice.academy_id != self.academy_id:
            raise ValidationError({'rent_invoice': 'Rent invoice must belong to the same academy.'})
        if self.rent_payment_id and self.rent_invoice_id and self.rent_payment.rent_invoice_id != self.rent_invoice_id:
            raise ValidationError({'rent_payment': 'Rent payment must belong to the same rent invoice.'})


class RentPaySchedule(models.Model):
    """Automation config for rent invoicing — one per location per billing type."""

    class BillingType(models.TextChoices):
        MONTHLY = 'MONTHLY', 'Monthly'
        DAILY = 'DAILY', 'Daily'
        SESSION = 'SESSION', 'Per Session'

    academy = models.ForeignKey(
        Academy,
        on_delete=models.CASCADE,
        related_name='rent_pay_schedules',
        db_index=True,
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        related_name='rent_pay_schedules',
        db_index=True,
    )
    billing_type = models.CharField(
        max_length=20,
        choices=BillingType.choices,
        db_index=True,
    )
    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        help_text='Auto-populated from FacilityRentConfig; override here if needed',
    )
    currency = models.CharField(max_length=3, default='AED')
    sessions_per_invoice = models.PositiveIntegerField(
        null=True,
        blank=True,
        help_text='SESSION only — how many sessions before invoice fires',
    )
    billing_day = models.PositiveIntegerField(
        null=True,
        blank=True,
        validators=[MinValueValidator(1), MaxValueValidator(28)],
        help_text='MONTHLY only — day of month invoice fires',
    )
    due_date_offset_days = models.PositiveIntegerField(
        default=30,
        help_text='Days after issued_date to set as due_date (e.g. 30 = NET 30)',
    )
    cycle_start_date = models.DateField(
        help_text='Automation ignores classes/dates before this date',
    )
    is_active = models.BooleanField(default=True, db_index=True)
    last_run_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_rent_pay_schedules'
        constraints = [
            models.UniqueConstraint(
                fields=['academy', 'location', 'billing_type'],
                name='unique_rent_pay_schedule_per_location_billing_type',
            )
        ]

    def __str__(self):
        return f"{self.location.name} — {self.billing_type}"

    def clean(self):
        if self.location_id and self.academy_id and self.location.academy_id != self.academy_id:
            raise ValidationError({'location': 'Location must belong to the same academy.'})

        bt = self.billing_type
        if bt == self.BillingType.SESSION:
            if not self.sessions_per_invoice:
                raise ValidationError(
                    {'sessions_per_invoice': 'Sessions per invoice is required for SESSION billing.'}
                )
            if self.billing_day is not None:
                raise ValidationError({'billing_day': 'Must be empty for SESSION billing.'})
        elif bt == self.BillingType.MONTHLY:
            if self.billing_day is None:
                raise ValidationError({'billing_day': 'Billing day is required for MONTHLY billing.'})
            if self.sessions_per_invoice is not None:
                raise ValidationError(
                    {'sessions_per_invoice': 'Must be empty for MONTHLY billing.'}
                )
        elif bt == self.BillingType.DAILY:
            if self.sessions_per_invoice is not None:
                raise ValidationError(
                    {'sessions_per_invoice': 'Must be empty for DAILY billing.'}
                )
            if self.billing_day is not None:
                raise ValidationError({'billing_day': 'Must be empty for DAILY billing.'})


class FacilitySessionCycle(models.Model):
    """Session counter for SESSION billing_type schedules."""

    schedule = models.ForeignKey(
        RentPaySchedule,
        on_delete=models.CASCADE,
        related_name='session_cycles',
    )
    cycle_number = models.PositiveIntegerField(default=1)
    sessions_counted = models.PositiveIntegerField(default=0)
    last_counted_date = models.DateField(
        null=True,
        blank=True,
        help_text='Prevents double-counting on reruns',
    )
    invoice = models.ForeignKey(
        RentInvoice,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='source_facility_cycle',
        help_text='Null until cycle fires; set on invoice generation',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_facility_session_cycles'
        constraints = [
            models.UniqueConstraint(
                fields=['schedule', 'cycle_number'],
                name='unique_facility_cycle_per_schedule',
            )
        ]

    def __str__(self):
        return f"{self.schedule_id} cycle {self.cycle_number}"


class RentPayScheduleRun(models.Model):
    """Audit log of rent pay schedule task executions."""

    class RunStatus(models.TextChoices):
        SUCCEEDED = 'SUCCEEDED', 'Succeeded'
        FAILED = 'FAILED', 'Failed'
        PARTIAL = 'PARTIAL', 'Partial'

    class TriggerSource(models.TextChoices):
        SCHEDULED = 'SCHEDULED', 'Scheduled'
        MANUAL = 'MANUAL', 'Manual'

    schedule = models.ForeignKey(
        RentPaySchedule,
        on_delete=models.CASCADE,
        related_name='runs',
    )
    run_at = models.DateTimeField(auto_now_add=True)
    invoices_created = models.PositiveIntegerField(default=0)
    status = models.CharField(max_length=20, choices=RunStatus.choices)
    triggered_by = models.CharField(
        max_length=20,
        choices=TriggerSource.choices,
        default=TriggerSource.SCHEDULED,
    )
    error_detail = models.TextField(blank=True)

    class Meta:
        db_table = 'tenant_rent_pay_schedule_runs'
        ordering = ['-run_at']

    def __str__(self):
        return f"{self.schedule_id} @ {self.run_at}"


class Bill(models.Model):
    """Running cost bill."""

    class Status(models.TextChoices):
        PENDING = 'PENDING', 'Pending'
        PAID = 'PAID', 'Paid'
        OVERDUE = 'OVERDUE', 'Overdue'
        CANCELLED = 'CANCELLED', 'Cancelled'

    academy = models.ForeignKey(
        Academy,
        on_delete=models.CASCADE,
        related_name='bills',
        db_index=True,
    )
    vendor_name = models.CharField(max_length=255)
    bill_number = models.CharField(max_length=100, blank=True, default='')
    total_amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal('0.00'),
        validators=[MinValueValidator(Decimal('0.00'))],
    )
    currency = models.CharField(max_length=3, default='USD')
    bill_date = models.DateField(default=timezone.localdate)
    due_date = models.DateField(null=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
        db_index=True,
    )
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_bills'
        ordering = ['-bill_date', '-created_at']
        indexes = [
            models.Index(fields=['academy', 'status']),
            models.Index(fields=['academy', 'bill_date']),
            models.Index(fields=['academy', 'due_date']),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['academy', 'bill_number'],
                condition=Q(bill_number__isnull=False) & ~Q(bill_number=''),
                name='unique_bill_number_per_academy_when_set',
            )
        ]

    def __str__(self):
        if self.bill_number:
            return f"{self.bill_number} - {self.vendor_name}"
        return f"Bill #{self.pk} - {self.vendor_name}"

    def recalculate_total(self):
        total = self.line_items.aggregate(total=Sum('line_total')).get('total')
        self.total_amount = total or Decimal('0.00')

    def update_status_for_due_date(self):
        if self.status != self.Status.PENDING:
            return
        today = timezone.now().date()
        if self.due_date and self.due_date < today:
            self.status = self.Status.OVERDUE

    def save(self, *args, **kwargs):
        self.full_clean()
        self.update_status_for_due_date()
        super().save(*args, **kwargs)


class InventoryItem(models.Model):
    """Inventory item owned by academy."""

    academy = models.ForeignKey(
        Academy,
        on_delete=models.CASCADE,
        related_name='inventory_items',
        db_index=True,
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    quantity = models.PositiveIntegerField(default=0)
    unit = models.CharField(max_length=30, blank=True)
    reorder_level = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_inventory_items'
        ordering = ['name']
        indexes = [
            models.Index(fields=['academy', 'name']),
            models.Index(fields=['academy', 'quantity']),
        ]
        constraints = [
            models.UniqueConstraint(
                fields=['academy', 'name'],
                name='unique_inventory_item_name_per_academy',
            )
        ]

    def __str__(self):
        return f"{self.name} ({self.quantity})"


class BillLineItem(models.Model):
    """Line item for bills."""

    bill = models.ForeignKey(
        Bill,
        on_delete=models.CASCADE,
        related_name='line_items',
        db_index=True,
    )
    description = models.CharField(max_length=500)
    quantity = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    unit_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
    )
    line_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
    )
    inventory_item = models.ForeignKey(
        InventoryItem,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='bill_line_items',
        db_index=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'tenant_bill_line_items'
        ordering = ['created_at']
        indexes = [
            models.Index(fields=['bill']),
            models.Index(fields=['inventory_item']),
        ]

    def __str__(self):
        return f"{self.description} ({self.quantity})"

    def clean(self):
        if self.inventory_item_id and self.inventory_item.academy_id != self.bill.academy_id:
            raise ValidationError({'inventory_item': 'Inventory item must belong to the same academy as the bill.'})

    def save(self, *args, **kwargs):
        unit_price = self.unit_price
        if not isinstance(unit_price, Decimal):
            unit_price = Decimal(str(unit_price))
        self.unit_price = unit_price
        self.line_total = Decimal(str(self.quantity)) * unit_price
        self.full_clean()
        super().save(*args, **kwargs)
