# Generated by Django 4.2.27 on 2026-01-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_onboardingstate_user_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('trial_days', models.IntegerField(default=0)),
                ('limits_json', models.JSONField(default=dict)),
                ('seat_based_pricing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='TRIAL', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('overrides_json', models.JSONField(blank=True, default=dict)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.academy')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['slug'], name='plans_slug_04002b_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'is_public'], name='plans_is_acti_dd5eef_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['academy', 'is_current'], name='subscriptio_academy_b491bf_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'is_current'], name='subscriptio_status_9b2228_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['start_at', 'end_at'], name='subscriptio_start_a_4e0643_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('academy',), name='unique_current_subscription_per_academy'),
        ),
    ]
