# Generated by Django 5.2.6 on 2026-03-16 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0005_ensure_academy_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('payment_date', models.DateField(db_index=True)),
                ('invoice_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('external_ref', models.CharField(blank=True, max_length=255)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_payments', to='tenants.academy')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'platform_payments',
                'indexes': [models.Index(fields=['payment_date'], name='platform_pa_payment_c0dae7_idx'), models.Index(fields=['academy', 'payment_date'], name='platform_pa_academy_1b4206_idx')],
            },
        ),
    ]
