# Generated by Django 4.2.27 on 2026-01-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_onboardingstate_user_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_used_bytes', models.BigIntegerField(db_index=True, default=0)),
                ('students_count', models.IntegerField(db_index=True, default=0)),
                ('coaches_count', models.IntegerField(db_index=True, default=0)),
                ('admins_count', models.IntegerField(db_index=True, default=0)),
                ('classes_count', models.IntegerField(db_index=True, default=0)),
                ('counts_computed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Tenant Usage',
                'verbose_name_plural': 'Tenant Usages',
                'db_table': 'tenant_usages',
            },
        ),
        migrations.CreateModel(
            name='TenantQuota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storage_bytes_limit', models.BigIntegerField(db_index=True, default=0)),
                ('max_students', models.IntegerField(db_index=True, default=0)),
                ('max_coaches', models.IntegerField(db_index=True, default=0)),
                ('max_admins', models.IntegerField(db_index=True, default=0)),
                ('max_classes', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Tenant Quota',
                'verbose_name_plural': 'Tenant Quotas',
                'db_table': 'tenant_quotas',
            },
        ),
    ]
