# Generated by Django 4.2.27 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantquota',
            name='storage_warning_threshold_pct',
            field=models.PositiveSmallIntegerField(
                default=80,
                help_text='Storage usage warning threshold percentage (0-99).',
            ),
        ),
    ]

