# Generated by Django 5.2.6 on 2026-03-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotas', '0002_storage_warning_threshold_pct'),
        ('tenants', '0007_academy_global_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_used_bytes', models.BigIntegerField()),
                ('db_size_bytes', models.BigIntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_snapshots', to='tenants.academy')),
            ],
            options={
                'db_table': 'storage_snapshots',
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
                'indexes': [models.Index(fields=['academy', 'recorded_at'], name='storage_sna_academy_4b2f41_idx')],
            },
        ),
    ]
