# Generated by Django 5.2.6 on 2026-01-18 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academy', 'coach'], name='tenant_clas_academy_f6c541_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academy', 'is_active'], name='tenant_clas_academy_333761_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academy', 'name'], name='tenant_clas_academy_451075_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academy', 'student'], name='tenant_enro_academy_c58a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academy', 'class_obj'], name='tenant_enro_academy_7975ab_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'class_obj'], name='tenant_enro_student_b87f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='tenant_enro_status_5bc33f_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ENROLLED')), fields=('student', 'class_obj'), name='unique_active_enrollment_per_student_class'),
        ),
    ]
