# Generated by Django 5.2.6 on 2026-01-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
        ('coaches', '0001_initial'),
        ('onboarding', '0001_initial'),
        ('tenants', '0002_onboardingstate_user_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='onboarding.location'),
        ),
        migrations.AddField(
            model_name='class',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='onboarding.sport'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academy', 'sport'], name='tenant_clas_academy_0da546_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academy', 'location'], name='tenant_clas_academy_c86a70_idx'),
        ),
    ]
