# Generated by Django 4.2.27 on 2026-01-19 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, help_text='Email address used for authentication', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('COACH', 'Coach'), ('PARENT', 'Parent')], db_index=True, help_text='User role within the academy', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Designates whether this user is active. Users must accept invite to become active.')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Designates whether this user has verified their email by accepting invite.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(help_text='Academy this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.academy')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'tenant_users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, help_text='Phone number for parent', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profiles', to='tenants.academy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'tenant_parent_profiles',
                'indexes': [models.Index(fields=['academy', 'is_active'], name='tenant_pare_academy_c58930_idx')],
            },
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='Hashed invite token', max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Token expiration timestamp')),
                ('used_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when token was used (null if unused)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to='tenants.academy')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this invite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_tokens', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Token',
                'verbose_name_plural': 'Invite Tokens',
                'db_table': 'tenant_invite_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='tenant_invi_token_h_2d823b_idx'), models.Index(fields=['user', 'used_at'], name='tenant_invi_user_id_68e13c_idx'), models.Index(fields=['expires_at', 'used_at'], name='tenant_invi_expires_e156f1_idx'), models.Index(fields=['academy'], name='tenant_invi_academy_c9b8a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, help_text='Coach type (e.g., Head Coach, Assistant Coach)', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profiles', to='tenants.academy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach Profile',
                'verbose_name_plural': 'Coach Profiles',
                'db_table': 'tenant_coach_profiles',
                'indexes': [models.Index(fields=['academy', 'is_active'], name='tenant_coac_academy_a4573d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to='tenants.academy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'db_table': 'tenant_admin_profiles',
                'indexes': [models.Index(fields=['academy', 'is_active'], name='tenant_admi_academy_8d8367_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='tenant_user_email_756120_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='tenant_user_role_c823a4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['academy', 'role'], name='tenant_user_academy_09d9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['academy', 'is_active'], name='tenant_user_academy_2e32b2_idx'),
        ),
    ]
