# Generated by Django 4.2.27 on 2026-01-19 13:59

from django.db import migrations


def add_location_if_missing(apps, schema_editor):
    """Add location_id to tenant_coach_profiles only if it does not exist (idempotent)."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        if connection.vendor == "sqlite":
            cursor.execute("PRAGMA table_info(tenant_coach_profiles)")
            columns = {row[1] for row in cursor.fetchall()}
            if "location_id" not in columns:
                cursor.execute("ALTER TABLE tenant_coach_profiles ADD COLUMN location_id integer NULL")
            # SQLite doesn't support adding FK constraints via ALTER TABLE in-place.
            cursor.execute(
                "CREATE INDEX IF NOT EXISTS tenant_coac_locatio_a29d5d_idx ON tenant_coach_profiles (location_id)"
            )
            return

        # Postgres / others
        cursor.execute(
            "ALTER TABLE tenant_coach_profiles ADD COLUMN IF NOT EXISTS location_id integer NULL"
        )
        if connection.vendor == "postgresql":
            cursor.execute(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'tenant_coach_profiles_location_id_fkey'
                    ) THEN
                        ALTER TABLE tenant_coach_profiles
                        ADD CONSTRAINT tenant_coach_profiles_location_id_fkey
                        FOREIGN KEY (location_id) REFERENCES tenant_locations(id) ON DELETE SET NULL;
                    END IF;
                END
                $$;
                """
            )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS tenant_coac_locatio_a29d5d_idx ON tenant_coach_profiles (location_id)"
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_location_if_missing, noop_reverse),
    ]

