# Generated by Django 4.2.27 on 2026-01-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='location',
            field=models.ForeignKey(
                blank=True,
                help_text='Primary location for this coach',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='coaches',
                to='onboarding.location',
            ),
        ),
        migrations.AddIndex(
            model_name='coachprofile',
            index=models.Index(fields=['location'], name='tenant_coac_locatio_a29d5d_idx'),
        ),
    ]

