# Generated by Django 5.2.6 on 2026-03-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLOUD', 'Cloud Infrastructure'), ('DOMAIN', 'Domain & DNS'), ('SERVER', 'Server / VPS'), ('SAAS', 'SaaS Tool'), ('LEGAL', 'Legal & Compliance'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('vendor_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('ONE_TIME', 'One-time'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operational_expenses',
                'indexes': [models.Index(fields=['paid_date', 'is_paid'], name='operational_paid_da_a6a5e1_idx'), models.Index(fields=['billing_cycle', 'category'], name='operational_billing_8718ae_idx')],
            },
        ),
    ]
