# Generated by Django 5.2.6 on 2026-01-18 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_initial'),
        ('coaches', '0001_initial'),
        ('students', '0001_initial'),
        ('tenants', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], db_index=True, default='PRESENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.academy')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='classes.class')),
                ('marked_by', models.ForeignKey(blank=True, help_text='User who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'tenant_attendance',
                'ordering': ['-date', 'student'],
                'indexes': [models.Index(fields=['academy', 'date'], name='tenant_atte_academy_a0c635_idx'), models.Index(fields=['academy', 'student', 'date'], name='tenant_atte_academy_1dce6f_idx'), models.Index(fields=['academy', 'class_obj', 'date'], name='tenant_atte_academy_ccd187_idx'), models.Index(fields=['status'], name='tenant_atte_status_d605c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'class_obj', 'date'), name='unique_attendance_per_student_class_date')],
            },
        ),
        migrations.CreateModel(
            name='CoachAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], db_index=True, default='PRESENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_attendance_records', to='tenants.academy')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_attendance_records', to='classes.class')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='coaches.coach')),
                ('marked_by', models.ForeignKey(blank=True, help_text='User who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_coach_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach Attendance',
                'verbose_name_plural': 'Coach Attendance Records',
                'db_table': 'tenant_coach_attendance',
                'ordering': ['-date', 'coach'],
                'indexes': [models.Index(fields=['academy', 'date'], name='tenant_coac_academy_529d84_idx'), models.Index(fields=['academy', 'coach', 'date'], name='tenant_coac_academy_06720e_idx'), models.Index(fields=['academy', 'class_obj', 'date'], name='tenant_coac_academy_a08a71_idx'), models.Index(fields=['status'], name='tenant_coac_status_2cd5e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('coach', 'class_obj', 'date'), name='unique_coach_attendance_per_coach_class_date')],
            },
        ),
    ]
