# Generated by Django 4.2.27 on 2026-01-19 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('onboarding_completed', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academy',
                'verbose_name_plural': 'Academies',
                'db_table': 'academies',
            },
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('current_step', models.IntegerField(db_index=True, default=1)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step_1_completed', models.BooleanField(default=False)),
                ('step_2_completed', models.BooleanField(default=False)),
                ('step_3_completed', models.BooleanField(default=False)),
                ('step_4_completed', models.BooleanField(default=False)),
                ('step_5_completed', models.BooleanField(default=False)),
                ('step_6_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to='tenants.academy')),
            ],
            options={
                'verbose_name': 'Onboarding State',
                'verbose_name_plural': 'Onboarding States',
                'db_table': 'onboarding_states',
            },
        ),
        migrations.AddIndex(
            model_name='academy',
            index=models.Index(fields=['slug'], name='academies_slug_5ea1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='academy',
            index=models.Index(fields=['onboarding_completed', 'is_active'], name='academies_onboard_07c9b8_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingstate',
            index=models.Index(fields=['academy', 'is_completed'], name='onboarding__academy_7f713d_idx'),
        ),
        migrations.AddIndex(
            model_name='onboardingstate',
            index=models.Index(fields=['current_step'], name='onboarding__current_965a6c_idx'),
        ),
    ]
