# Generated by Django (manual edit) on 2026-03-18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_onboarding_step_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="academy",
            name="global_tax_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="academy",
            name="global_tax_rate_percent",
            field=models.DecimalField(
                default=Decimal("0.00"),
                max_digits=6,
                decimal_places=2,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]

