# Generated by Django 4.2.29 on 2026-03-25 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_academy_global_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyWhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('send_on_invoice_created', models.BooleanField(default=True)),
                ('send_on_receipt_created', models.BooleanField(default=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('waba_id', models.CharField(blank=True, max_length=64)),
                ('invoice_template_name', models.CharField(default='academy_invoice_created', max_length=128)),
                ('receipt_template_name', models.CharField(default='academy_receipt_issued', max_length=128)),
                ('template_language', models.CharField(default='en', max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='tenants.academy')),
                ('configured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_whatsapp_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academy WhatsApp Configuration',
                'verbose_name_plural': 'Academy WhatsApp Configurations',
                'db_table': 'platform_academy_whatsapp_config',
            },
        ),
    ]
