# Generated by Django 5.2.6 on 2026-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emirates_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
