# Generated by Django 4.2.27 on 2026-01-19 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_onboardingstate_user_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PLAN_CHANGE', 'Plan Change'), ('QUOTA_UPDATE', 'Quota Update')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(choices=[('ACADEMY', 'Academy'), ('SUBSCRIPTION', 'Subscription'), ('PLAN', 'Plan'), ('QUOTA', 'Quota')], db_index=True, max_length=20)),
                ('resource_id', models.CharField(db_index=True, max_length=255)),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('academy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.academy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['academy', 'created_at'], name='audit_logs_academy_b49a87_idx'), models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx')],
            },
        ),
    ]
