# Generated by Django 4.2.27 on 2026-01-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_error_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_created_008b9a_idx',
            old_name='error_logs_created__2e0c0b_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_status__348535_idx',
            old_name='error_logs_status__d2d2b1_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_code_0ce88b_idx',
            old_name='error_logs_code_cr_3a0e97_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_academy_32c8c5_idx',
            old_name='error_logs_academ_8c8f78_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='error_logs_user_id_71f3b9_idx',
            old_name='error_logs_user_cr_57c5c6_idx',
        ),
    ]
