# Generated by Django 5.2.6 on 2026-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_rename_error_logs_created__2e0c0b_idx_error_logs_created_008b9a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(choices=[('ACADEMY', 'Academy'), ('SUBSCRIPTION', 'Subscription'), ('PLAN', 'Plan'), ('QUOTA', 'Quota'), ('USER', 'User')], db_index=True, max_length=20),
        ),
    ]
